BankApp/Controllers/HomeController.cs
using Bank.Models;
using System;
using System.Web.Mvc;

namespace Bank.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.FormSubmited = 0;

            return View();
        }

        //JDR: For ContactUsForm
        [HttpPost]
        public ActionResult Contact(String FormName, String FormEmail, String FormPhone, String FormMessage)
        {
            //JDR: Logic to store this in DB or sent to admin
            //...LOGIC...FORM DATA VALIDATION

            ViewBag.FormSubmited = 1;
            ViewBag.FormNotification = FormName + ", we will contact you as soon as possible.";

            return View();
        }
    }
}

BankApp/Controllers/LoansController.cs
using Bank.Models;
using Bank.ViewModels;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bank.Controllers
{
    public class LoansController : Controller
    {
        // GET: Loan
        public ActionResult Index()
        {
            //return RedirectToAction("Index", "Home");    //JDR: Redirect to HomePage
            return View("~/Views/Home/Index.cshtml");
        }

        public ActionResult RequestLoan()
        {
            if (!UserAccount.IsLoggedIn(this)) return RedirectToAction("SendToLogin", "Account", new { Something = "" });

            return View();
        }

        [HttpPost]
        public ActionResult RequestLoan(Loans_RequestLoan_VM Model)
        {
            if (!UserAccount.IsLoggedIn(this)) return RedirectToAction("SendToLogin", "Account", new { Something = "" });

            if (!ModelState.IsValid) return View(Model);

            int UserID = (UserAccount.ActiveUser != null) ? UserAccount.ActiveUser.ID : 1027/*For Debug*/;

            var Loan = new  LoanRequest().New();

            Loan.UserID         = UserID;
            Loan.SocialSecurity = Model.SocialSecurity;
            Loan.Income         = Model.Income;
            Loan.Employer       = Model.Employer;
            Loan.JobTitle       = Model.JobTitle;
            Loan.EmploymentType = Model.EmploymentType;
            Loan.Amount         = Model.Amount;
            Loan.Terms          = Model.Terms;
            Loan.DownPayment    = Model.DownPayment;
            Loan.LoanType       = Model.LoanType;
            Loan.Status         = "Pending";

            if (!Loan.Save())
            {
                TempData["AlertTag"]     = "danger";
                TempData["AlertLabel"]   = "Error: ";
                TempData["AlertMessage"] = "Loan request could not be saved.";

                return View(Model);
            }

            var Score = CreditScore.GetByUserID(UserID).TransUnion;

            //JDR: Call Api to calclate Result
            // ... Code ...

            var LoanProperties = new
            {
                Terms       = Model.Terms,
                Amount      = Model.Amount,
                Income      = Model.Income,
                DownPayment = Model.DownPayment,
                CreditScore = Score,
                APR         = LoanResult.CalculateAPR((int)Score, (int)Model.Terms),
            };

            var Result = new LoanResult().New();

            Result.RequestID        = Loan.ID;
            Result.Amount           = Model.Amount;
            Result.Term             = Model.Terms;
            Result.ResolutionDate   = DateTime.Now;
            Result.CreditScore      = LoanProperties.CreditScore;
            Result.APR              = LoanProperties.APR;
            Result.MonthlyPayment   = LoanResult.CalculateMonthlyPayment(LoanProperties);
            Result.Decision         = "Pending";
            Result.Comments         = "Loan has been recived and is pending review.";

            double IncomeYrTotal  = (double) Model.Income;
            double DebtMonthTotal = (double) Result.MonthlyPayment;

            var UserLoans = LoanRequest.GetLoanRequestsByUserID(UserID);

            //JDR: Factor in other loans to debt equation
            foreach (LoanRequest LoanElement in UserLoans)
            {
                //if (!LoanElement.Active()) continue;
                if (LoanElement.Status.Trim() != "Approved") continue;

                LoanResult ResultElement = LoanElement.GetLoanResults();

                if (ResultElement == null) continue;

                DebtMonthTotal += (double)ResultElement.MonthlyPayment;
            }

            var DebtToIncome = LoanResult.CalculateDebtToIncomePercent(IncomeYrTotal, DebtMonthTotal);

            //JDR: Save Loan approved/denied result
            if (LoanResult.IsLoanApproved(DebtToIncome, Model.LoanType))
            {
                Loan.Status     = "Approved";
                Result.Decision = "Approved";
                Result.Comments = "Loan has been approved for a total of " + Result.Amount.ToString("$###,###.##") + ".";
            }
            else
            {
                Loan.Status     = "Denied";
                Result.Decision = "Denied";
                Result.Comments = "Loan has beed denied do to debt to income ratio.";

                Result.APR = 0.0;
                Result.MonthlyPayment = 0.0;
            }

            Loan.Save();

            if (!Result.Save())
            {
                TempData["AlertTag"] = "danger";
                TempData["AlertLabel"] = "Error: ";
                TempData["AlertMessage"] = "Loan request cound not save/compute result of request.";

                return RedirectToAction("Dashboard", "Account");
            }

            /*//DEBUG
            TempData["AlertMessage"] = "";
            TempData["AlertMessage"] += DEBUG.ObjectToString(Loan)           + "<hr>";
            TempData["AlertMessage"] += DEBUG.ObjectToString(Result)         + "<hr>";
            TempData["AlertMessage"] += DEBUG.ObjectToString(LoanProperties) + "<hr>";
            TempData["AlertMessage"] += "Result.MonthlyPayment   = " + Result.MonthlyPayment + "<hr>";
            TempData["AlertMessage"] += "IncomeYrTotal  = "+ IncomeYrTotal  + "<hr>";
            TempData["AlertMessage"] += "DebtMonthTotal = " + DebtMonthTotal + "<hr>";
            TempData["AlertMessage"] += "DebtToIncome   = " + DebtToIncome   + "<hr>";
            return View();
            //*/

            TempData["AlertTag"] = "success";
            TempData["AlertLabel"] = "Success!: ";
            TempData["AlertMessage"] = "Loan request has been submited.";


            return RedirectToAction("Dashboard", "Account");
        }
    }
}

BankApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<!--JDR: Banner-->
<div class="row"><img class="col-md-12 img-grayscale" src="@Url.Content("~/Content/Images/BannerInvest.png")"></div>

<div class="bank-bank-body-content">
    <h1 class="bank-header">@ViewBag.Title</h1>

    <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla rhoncus, libero a rutrum consequat, ipsum odio accumsan nibh, blandit sodales mi massa quis justo. Donec cursus nulla enim, at mattis ante volutpat non. Morbi in lectus non ipsum consectetur mollis nec eu erat. Curabitur quis turpis magna. Nam at odio at dui tincidunt luctus vitae et ipsum. Vivamus libero arcu, tincidunt a semper eget, dapibus sit amet odio. Aliquam pellentesque eget metus ut luctus. Duis quam ex, sodales at ipsum sed, viverra lobortis metus
    </div>

    <div class="loan-options-container row vertical-divide text-center">
        <div class="col-md-4">
            <h3 class="loan-options-title">Personal Loan</h3>
            <div>
                Personal loan with lower interest rate than on an unsecured personal loan.
            </div>
        </div>
        <div class="col-md-4">
            <h3 class="loan-options-title">Auto Loan</h3>
            <div>
                Obtain your auto insurance and readside assistance product 100% online
            </div>
        </div>
        <div class="col-md-4">
            <h3 class="loan-options-title">Home Loan</h3>
            <div>
                Recive an instant pre-approval for your mortgage loan.
            </div>
        </div>
    </div>

    <div>
        Sed enim justo, vulputate ut magna iaculis, vestibulum aliquam ante. Fusce porttitor augue ut leo commodo, eu imperdiet augue aliquet. Etiam ut libero risus. In molestie eget arcu at malesuada. Curabitur ac arcu ut lorem varius gravida. Quisque euismod arcu ut mattis venenatis. Proin vitae blandit sem. Mauris iaculis porta elementum. Etiam finibus bibendum risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris et molestie elit. Mauris at viverra neque, in tristique lorem. Cras et aliquam enim.
    </div>
</div>

BankApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<!--JDR: TODO: Actualy setup googlemaps div here for current location-->
<div class="row">
    <iframe class="google-maps float-left col-12 col-sm-12 col-md-12 col-lg-12" height="350" id="gmap_canvas" src="https://maps.google.com/maps?q=Dxc%20Isabela&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
</div>

<div class="contact-container row vertical-divide">
    <div class="col-md-8">
        <div class="bank-header">Our Locations</div>

        <div class="bank-title">Bank, Ink.</div>

        <address>
            1355 Market  Street, Suit 900<br />
            San Francisco, CA 94103<br />
            P: (123) 456-7890
        </address>

        <div class="bank-title">Bank, Ink.</div>

        <address>
            689 Industrial Avenue<br />
            Isabela, PR 00662<br />
            P: (123) 456-7890
        </address>
    </div>
    <div class="col-md-4">
        <!--JDR: TODO: Set partial view someplace for contact form-->
        @Html.Partial("_ContactUsForm")
    </div>
</div>

BankApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!--JDR: ASP.NET Uses bootstrap for carousel-->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="@Url.Content("~/Content/Images/BannerInvestorRelations.png")" alt="">
        </div>

        <div class="item">
            <img src="@Url.Content("~/Content/Images/BannerManufacturing.png")" alt="">
        </div>

        <div class="item">
            <img src="@Url.Content("~/Content/Images/BannerRansomware.png")" alt="">
        </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<!--JDR: Set loan types btn UI-->
<!--JDR: TODO: Set gray filter in css later-->
<div class="loan-options-container row text-center">
    <div class="col-md-4">
        <img class="loan-options-img" src="@Url.Content("~/Content/Images/LoanPersonal.jpg")" alt=""> <!--JDR: Image very BIG should reduce quality in real world application-->
        <h3 class="loan-options-title">Personal Loan</h3>
        <div class="loan-options-text">
            Personal loan with lower interest rate than on an unsecured personal loan.
        </div>
        <a href="@Url.Action("RequestLoan", "Loans", new { TypeLoan = "PL" })" class="btn bank-yellow-btn">APPLY NOW</a>
    </div>
    <div class="col-md-4">
        <img class="loan-options-img" src="@Url.Content("~/Content/Images/LoanAuto.jpg")" alt=""> <!--JDR: Image very BIG should reduce quality in real world application-->
        <h3 class="loan-options-title">Auto Loan</h3>
        <div class="loan-options-text">
            Obtain your auto insurance and readside assistance product 100% online
        </div>
        <a href="@Url.Action("RequestLoan", "Loans", new { TypeLoan = "AL" })" class="btn bank-yellow-btn">APPLY NOW</a>
    </div>
    <div class="col-md-4">
        <img class="loan-options-img" src="@Url.Content("~/Content/Images/LoanHome.jpg")" alt=""> <!--JDR: Image very BIG should reduce quality in real world application-->
        <h3 class="loan-options-title">Home Loan</h3>
        <div class="loan-options-text">
            Recive an instant pre-approval for your mortgage loan.
        </div>
        <a href="@Url.Action("RequestLoan", "Loans", new { TypeLoan = "HL" })" class="btn bank-yellow-btn align-bottom align-text-bottom">APPLY NOW</a>
    </div>
</div>

<!--JDR:Banner-->
<div class="loan-banner row">
    <div class="col-md-4">
        <img src="https://via.placeholder.com/270x200" alt=""> <!--JDR: Placeholder-->
    </div>
    <div class="col-md-8">
        <h1>First feature heading. It'll blow your mind.</h1>
        <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc pellentesque, erat consectetur aliquet ullamcorper, massa ligula pellentesque magna, nec maximus turpis leo vel ante. Suspendisse nec felis vestibulum, viverra justo.
        </div>
    </div>
</div>